services:
    springboot:
        build:
            context: .
            dockerfile: Dockerfile
        image: "internhub-chatbot:latest"
        container_name: "chatbot"
        restart: unless-stopped
        ports:
            - "8081:8080"
        volumes:
            - ./documents:/app/documents  # Mount thư mục 'documents' vào container
        networks:
            - chatbot-network
        environment:
            - etl.file.input-directory=/app/documents  # Cập nhật đường dẫn trong container
            - ollama.api.endpoint=http://ollama:11434
            - chroma.api.endpoint=http://chroma:8000
        env_file:
            - .env.docker
        depends_on:
            - chroma

    chroma:
        image: "ghcr.io/chroma-core/chroma:1.0.12"
        container_name: "chroma-db"
        restart: unless-stopped
        ports:
#            - "8000:8000"
            - "8001:8000"
        volumes:
            - chroma-data:/chroma
        networks:
            - chatbot-network
        environment:
            - CHROMA_DB_DIR=/chroma
        depends_on:
            - ollama

    ollama:
        image: "ollama/ollama:latest"
        container_name: "ollama"
        restart: unless-stopped
        ports:
            - "11434:11434"
        volumes:
            - ./ollama-data:/root/.ollama
        networks:
            - chatbot-network
#        volumes:
#            - C:\ollama-data:/root/.ollama
#        deploy:
#            resources:
#                reservations:
#                    devices:
#                        - driver: nvidia
#                          count: all
#                          capabilities: [gpu]

volumes:
    chroma-data:
        driver: local

networks:
    chatbot-network:
        driver: bridge
